Update copy-and-paste.md
Without the 'async' modifier the last two code snippets cause error CS4034: "The 'await' operator can only be used within an async lambda expression. Consider marking this lambda expression with the 'async' modifier."